package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnomPrgDvId generated by hbm2java
 */
@Embeddable
public class AnomPrgDvId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5836595730637400187L;
	private String dataview;
	private String programs;
	private String version;
	private String system;

	public AnomPrgDvId() {
	}

	public AnomPrgDvId(String dataview, String programs, String version,
			String system) {
		this.dataview = dataview;
		this.programs = programs;
		this.version = version;
		this.system = system;
	}

	@Column(name = "DATAVIEW", length = 50)
	public String getDataview() {
		return this.dataview;
	}

	public void setDataview(String dataview) {
		this.dataview = dataview;
	}

	@Column(name = "PROGRAMS", length = 50)
	public String getPrograms() {
		return this.programs;
	}

	public void setPrograms(String programs) {
		this.programs = programs;
	}

	@Column(name = "VERSION", length = 10)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "SYSTEM", length = 10)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnomPrgDvId))
			return false;
		AnomPrgDvId castOther = (AnomPrgDvId) other;

		return ((this.getDataview() == castOther.getDataview()) || (this
				.getDataview() != null && castOther.getDataview() != null && this
				.getDataview().equals(castOther.getDataview())))
				&& ((this.getPrograms() == castOther.getPrograms()) || (this
						.getPrograms() != null
						&& castOther.getPrograms() != null && this
						.getPrograms().equals(castOther.getPrograms())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getSystem() == castOther.getSystem()) || (this
						.getSystem() != null && castOther.getSystem() != null && this
						.getSystem().equals(castOther.getSystem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDataview() == null ? 0 : this.getDataview().hashCode());
		result = 37 * result
				+ (getPrograms() == null ? 0 : this.getPrograms().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getSystem() == null ? 0 : this.getSystem().hashCode());
		return result;
	}

}
