package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnomRunPrgId generated by hbm2java
 */
@Embeddable
public class AnomRunPrgId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8890231101257499875L;
	private String jobAppel;
	private String programs;
	private String system;

	public AnomRunPrgId() {
	}

	public AnomRunPrgId(String jobAppel, String programs, String system) {
		this.jobAppel = jobAppel;
		this.programs = programs;
		this.system = system;
	}

	@Column(name = "JOB_APPEL", length = 50)
	public String getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(String jobAppel) {
		this.jobAppel = jobAppel;
	}

	@Column(name = "PROGRAMS", length = 50)
	public String getPrograms() {
		return this.programs;
	}

	public void setPrograms(String programs) {
		this.programs = programs;
	}

	@Column(name = "SYSTEM", length = 50)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnomRunPrgId))
			return false;
		AnomRunPrgId castOther = (AnomRunPrgId) other;

		return ((this.getJobAppel() == castOther.getJobAppel()) || (this
				.getJobAppel() != null && castOther.getJobAppel() != null && this
				.getJobAppel().equals(castOther.getJobAppel())))
				&& ((this.getPrograms() == castOther.getPrograms()) || (this
						.getPrograms() != null
						&& castOther.getPrograms() != null && this
						.getPrograms().equals(castOther.getPrograms())))
				&& ((this.getSystem() == castOther.getSystem()) || (this
						.getSystem() != null && castOther.getSystem() != null && this
						.getSystem().equals(castOther.getSystem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobAppel() == null ? 0 : this.getJobAppel().hashCode());
		result = 37 * result
				+ (getPrograms() == null ? 0 : this.getPrograms().hashCode());
		result = 37 * result
				+ (getSystem() == null ? 0 : this.getSystem().hashCode());
		return result;
	}

}
