package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnomRunPrg generated by hbm2java
 */
@Entity
@Table(name = "ANOM_RUN_PRG", schema = "INTEGRATEUR")
public class AnomRunPrg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4955740056084072797L;
	private AnomRunPrgId id;
	private JobAppel jobAppel;

	public AnomRunPrg() {
	}

	public AnomRunPrg(AnomRunPrgId id) {
		this.id = id;
	}

	public AnomRunPrg(AnomRunPrgId id, JobAppel jobAppel) {
		this.id = id;
		this.jobAppel = jobAppel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobAppel", column = @Column(name = "JOB_APPEL", length = 50)),
			@AttributeOverride(name = "programs", column = @Column(name = "PROGRAMS", length = 50)),
			@AttributeOverride(name = "system", column = @Column(name = "SYSTEM", length = 50)) })
	public AnomRunPrgId getId() {
		return this.id;
	}

	public void setId(AnomRunPrgId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_APPEL", insertable = false, updatable = false)
	public JobAppel getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(JobAppel jobAppel) {
		this.jobAppel = jobAppel;
	}

}
