package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cft generated by hbm2java
 */
@Entity
@Table(name = "CFT", schema = "INTEGRATEUR")
public class Cft implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7410170446518619695L;
	private CftId id;
	private JobAppel jobAppel;

	public Cft() {
	}

	public Cft(CftId id) {
		this.id = id;
	}

	public Cft(CftId id, JobAppel jobAppel) {
		this.id = id;
		this.jobAppel = jobAppel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobAppel", column = @Column(name = "JOB_APPEL", length = 50)),
			@AttributeOverride(name = "part", column = @Column(name = "PART", length = 50)),
			@AttributeOverride(name = "idf", column = @Column(name = "IDF", length = 50)),
			@AttributeOverride(name = "parm", column = @Column(name = "PARM", length = 50)) })
	public CftId getId() {
		return this.id;
	}

	public void setId(CftId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_APPEL", insertable = false, updatable = false)
	public JobAppel getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(JobAppel jobAppel) {
		this.jobAppel = jobAppel;
	}

}
