package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CftId generated by hbm2java
 */
@Embeddable
public class CftId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2097965210195047232L;
	private String jobAppel;
	private String part;
	private String idf;
	private String parm;

	public CftId() {
	}

	public CftId(String jobAppel, String part, String idf, String parm) {
		this.jobAppel = jobAppel;
		this.part = part;
		this.idf = idf;
		this.parm = parm;
	}

	@Column(name = "JOB_APPEL", length = 50)
	public String getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(String jobAppel) {
		this.jobAppel = jobAppel;
	}

	@Column(name = "PART", length = 50)
	public String getPart() {
		return this.part;
	}

	public void setPart(String part) {
		this.part = part;
	}

	@Column(name = "IDF", length = 50)
	public String getIdf() {
		return this.idf;
	}

	public void setIdf(String idf) {
		this.idf = idf;
	}

	@Column(name = "PARM", length = 50)
	public String getParm() {
		return this.parm;
	}

	public void setParm(String parm) {
		this.parm = parm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CftId))
			return false;
		CftId castOther = (CftId) other;

		return ((this.getJobAppel() == castOther.getJobAppel()) || (this
				.getJobAppel() != null && castOther.getJobAppel() != null && this
				.getJobAppel().equals(castOther.getJobAppel())))
				&& ((this.getPart() == castOther.getPart()) || (this.getPart() != null
						&& castOther.getPart() != null && this.getPart()
						.equals(castOther.getPart())))
				&& ((this.getIdf() == castOther.getIdf()) || (this.getIdf() != null
						&& castOther.getIdf() != null && this.getIdf().equals(
						castOther.getIdf())))
				&& ((this.getParm() == castOther.getParm()) || (this.getParm() != null
						&& castOther.getParm() != null && this.getParm()
						.equals(castOther.getParm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobAppel() == null ? 0 : this.getJobAppel().hashCode());
		result = 37 * result
				+ (getPart() == null ? 0 : this.getPart().hashCode());
		result = 37 * result
				+ (getIdf() == null ? 0 : this.getIdf().hashCode());
		result = 37 * result
				+ (getParm() == null ? 0 : this.getParm().hashCode());
		return result;
	}

}
