package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatabaseAwb generated by hbm2java
 */
@Entity
@Table(name = "DATABASE_AWB", schema = "INTEGRATEUR")
public class DatabaseAwb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 791421160035486742L;
	private String name;
	private String dbid;
	private String userCatalogue;
	private Set<AreaAwb> areaAwbs = new HashSet<AreaAwb>(0);

	public DatabaseAwb() {
	}

	public DatabaseAwb(String name) {
		this.name = name;
	}

	public DatabaseAwb(String name, String dbid, String userCatalogue,
			Set<AreaAwb> areaAwbs) {
		this.name = name;
		this.dbid = dbid;
		this.userCatalogue = userCatalogue;
		this.areaAwbs = areaAwbs;
	}

	@Id
	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DBID", length = 50)
	public String getDbid() {
		return this.dbid;
	}

	public void setDbid(String dbid) {
		this.dbid = dbid;
	}

	@Column(name = "USER_CATALOGUE", length = 50)
	public String getUserCatalogue() {
		return this.userCatalogue;
	}

	public void setUserCatalogue(String userCatalogue) {
		this.userCatalogue = userCatalogue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "databaseAwb")
	public Set<AreaAwb> getAreaAwbs() {
		return this.areaAwbs;
	}

	public void setAreaAwbs(Set<AreaAwb> areaAwbs) {
		this.areaAwbs = areaAwbs;
	}

}
