package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataviewIdeal generated by hbm2java
 */
@Entity
@Table(name = "DATAVIEW_IDEAL", schema = "INTEGRATEUR")
public class DataviewIdeal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8147141083296263282L;
	private String dataview;
	private Set<RelatIdeal> relatIdeals = new HashSet<RelatIdeal>(0);

	public DataviewIdeal() {
	}

	public DataviewIdeal(String dataview) {
		this.dataview = dataview;
	}

	public DataviewIdeal(String dataview, Set<RelatIdeal> relatIdeals) {
		this.dataview = dataview;
		this.relatIdeals = relatIdeals;
	}

	@Id
	@Column(name = "DATAVIEW", unique = true, nullable = false, length = 50)
	public String getDataview() {
		return this.dataview;
	}

	public void setDataview(String dataview) {
		this.dataview = dataview;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataviewIdeal")
	public Set<RelatIdeal> getRelatIdeals() {
		return this.relatIdeals;
	}

	public void setRelatIdeals(Set<RelatIdeal> relatIdeals) {
		this.relatIdeals = relatIdeals;
	}

}
