package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataviewDatacom generated by hbm2java
 */
@Entity
@Table(name = "DATAVIEW_DATACOM", schema = "INTEGRATEUR")
public class DataviewDatacom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5007714729252679144L;
	private String dataview;
	private TableAwb tableAwb;
	private Set<RelatDatacom> relatDatacoms = new HashSet<RelatDatacom>(0);

	public DataviewDatacom() {
	}

	public DataviewDatacom(String dataview, TableAwb tableAwb) {
		this.dataview = dataview;
		this.tableAwb = tableAwb;
	}

	public DataviewDatacom(String dataview, TableAwb tableAwb,
			Set<RelatDatacom> relatDatacoms) {
		this.dataview = dataview;
		this.tableAwb = tableAwb;
		this.relatDatacoms = relatDatacoms;
	}

	@Id
	@Column(name = "DATAVIEW", unique = true, nullable = false, length = 50)
	public String getDataview() {
		return this.dataview;
	}

	public void setDataview(String dataview) {
		this.dataview = dataview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TABL", nullable = false)
	public TableAwb getTableAwb() {
		return this.tableAwb;
	}

	public void setTableAwb(TableAwb tableAwb) {
		this.tableAwb = tableAwb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataviewDatacom")
	public Set<RelatDatacom> getRelatDatacoms() {
		return this.relatDatacoms;
	}

	public void setRelatDatacoms(Set<RelatDatacom> relatDatacoms) {
		this.relatDatacoms = relatDatacoms;
	}

}
