package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobAppel generated by hbm2java
 */
@Entity
@Table(name = "JOB_APPEL", schema = "INTEGRATEUR")
public class JobAppel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7400087232438079559L;
	private String jobAppel;
	private String job;
	private Set<Sli> slis = new HashSet<Sli>(0);
	private Set<RunPrg> runPrgs = new HashSet<RunPrg>(0);
	private Set<AnomRunPrg> anomRunPrgs = new HashSet<AnomRunPrg>(0);
	private Set<Urt> urts = new HashSet<Urt>(0);
	private Set<Cft> cfts = new HashSet<Cft>(0);

	public JobAppel() {
	}

	public JobAppel(String jobAppel, String job) {
		this.jobAppel = jobAppel;
		this.job = job;
	}

	public JobAppel(String jobAppel, String job, Set<Sli> slis,
			Set<RunPrg> runPrgs, Set<AnomRunPrg> anomRunPrgs, Set<Urt> urts,
			Set<Cft> cfts) {
		this.jobAppel = jobAppel;
		this.job = job;
		this.slis = slis;
		this.runPrgs = runPrgs;
		this.anomRunPrgs = anomRunPrgs;
		this.urts = urts;
		this.cfts = cfts;
	}

	@Id
	@Column(name = "JOB_APPEL", unique = true, nullable = false, length = 50)
	public String getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(String jobAppel) {
		this.jobAppel = jobAppel;
	}

	@Column(name = "JOB", nullable = false, length = 50)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobAppel")
	public Set<Sli> getSlis() {
		return this.slis;
	}

	public void setSlis(Set<Sli> slis) {
		this.slis = slis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobAppel")
	public Set<RunPrg> getRunPrgs() {
		return this.runPrgs;
	}

	public void setRunPrgs(Set<RunPrg> runPrgs) {
		this.runPrgs = runPrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobAppel")
	public Set<AnomRunPrg> getAnomRunPrgs() {
		return this.anomRunPrgs;
	}

	public void setAnomRunPrgs(Set<AnomRunPrg> anomRunPrgs) {
		this.anomRunPrgs = anomRunPrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobAppel")
	public Set<Urt> getUrts() {
		return this.urts;
	}

	public void setUrts(Set<Urt> urts) {
		this.urts = urts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobAppel")
	public Set<Cft> getCfts() {
		return this.cfts;
	}

	public void setCfts(Set<Cft> cfts) {
		this.cfts = cfts;
	}

}
