package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programs generated by hbm2java
 */
@Entity
@Table(name = "PROGRAMS", schema = "INTEGRATEUR")
public class Programs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProgramsId id;
	private String status;
	private String dateCreated;
	private String dateModified;
	private Set<RunPrg> runPrgs = new HashSet<RunPrg>(0);
	private Set<RelatDatacom> relatDatacoms = new HashSet<RelatDatacom>(0);
	private Set<RelatIdeal> relatIdeals = new HashSet<RelatIdeal>(0);
	private Set<UseReport> useReports = new HashSet<UseReport>(0);
	private Set<UsePgm> usePgms = new HashSet<UsePgm>(0);
	private Set<UsePanel> usePanels = new HashSet<UsePanel>(0);

	public Programs() {
	}

	public Programs(ProgramsId id) {
		this.id = id;
	}

	public Programs(ProgramsId id, String status, String dateCreated,
			String dateModified, Set<RunPrg> runPrgs,
			Set<RelatDatacom> relatDatacoms, Set<RelatIdeal> relatIdeals,
			Set<UseReport> useReports, Set<UsePgm> usePgms,
			Set<UsePanel> usePanels) {
		this.id = id;
		this.status = status;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.runPrgs = runPrgs;
		this.relatDatacoms = relatDatacoms;
		this.relatIdeals = relatIdeals;
		this.useReports = useReports;
		this.usePgms = usePgms;
		this.usePanels = usePanels;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 50)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false, length = 50)),
			@AttributeOverride(name = "system", column = @Column(name = "SYSTEM", nullable = false, length = 50)) })
	public ProgramsId getId() {
		return this.id;
	}

	public void setId(ProgramsId id) {
		this.id = id;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DATE_CREATED", length = 50)
	public String getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(String dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "DATE_MODIFIED", length = 50)
	public String getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(String dateModified) {
		this.dateModified = dateModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<RunPrg> getRunPrgs() {
		return this.runPrgs;
	}

	public void setRunPrgs(Set<RunPrg> runPrgs) {
		this.runPrgs = runPrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<RelatDatacom> getRelatDatacoms() {
		return this.relatDatacoms;
	}

	public void setRelatDatacoms(Set<RelatDatacom> relatDatacoms) {
		this.relatDatacoms = relatDatacoms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<RelatIdeal> getRelatIdeals() {
		return this.relatIdeals;
	}

	public void setRelatIdeals(Set<RelatIdeal> relatIdeals) {
		this.relatIdeals = relatIdeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<UseReport> getUseReports() {
		return this.useReports;
	}

	public void setUseReports(Set<UseReport> useReports) {
		this.useReports = useReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<UsePgm> getUsePgms() {
		return this.usePgms;
	}

	public void setUsePgms(Set<UsePgm> usePgms) {
		this.usePgms = usePgms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<UsePanel> getUsePanels() {
		return this.usePanels;
	}

	public void setUsePanels(Set<UsePanel> usePanels) {
		this.usePanels = usePanels;
	}
@Override
public String toString() {
	// TODO Auto-generated method stub
	return this.id+"";
}
}
