package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatIdeal generated by hbm2java
 */
@Entity
@Table(name = "RELAT_IDEAL", schema = "INTEGRATEUR")
public class RelatIdeal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6017489685275414907L;
	private RelatIdealId id;
	private Programs programs;
	private DataviewIdeal dataviewIdeal;

	public RelatIdeal() {
	}

	public RelatIdeal(RelatIdealId id, Programs programs,
			DataviewIdeal dataviewIdeal) {
		this.id = id;
		this.programs = programs;
		this.dataviewIdeal = dataviewIdeal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dataview", column = @Column(name = "DATAVIEW", nullable = false, length = 50)),
			@AttributeOverride(name = "programs", column = @Column(name = "PROGRAMS", nullable = false, length = 50)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false, length = 50)),
			@AttributeOverride(name = "system", column = @Column(name = "SYSTEM", nullable = false, length = 50)) })
	public RelatIdealId getId() {
		return this.id;
	}

	public void setId(RelatIdealId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PROGRAMS", referencedColumnName = "NAME", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "VERSION", referencedColumnName = "VERSION", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SYSTEM", referencedColumnName = "SYSTEM", nullable = false, insertable = false, updatable = false) })
	public Programs getPrograms() {
		return this.programs;
	}

	public void setPrograms(Programs programs) {
		this.programs = programs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATAVIEW", nullable = false, insertable = false, updatable = false)
	public DataviewIdeal getDataviewIdeal() {
		return this.dataviewIdeal;
	}

	public void setDataviewIdeal(DataviewIdeal dataviewIdeal) {
		this.dataviewIdeal = dataviewIdeal;
	}

}
