package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatSliSched generated by hbm2java
 */
@Entity
@Table(name = "RELAT_SLI_SCHED", schema = "INTEGRATEUR")
public class RelatSliSched implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1103572933621829462L;
	private RelatSliSchedId id;
	private Scheduler scheduler;
	private Sli sli;

	public RelatSliSched() {
	}

	public RelatSliSched(RelatSliSchedId id, Scheduler scheduler, Sli sli) {
		this.id = id;
		this.scheduler = scheduler;
		this.sli = sli;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "job", column = @Column(name = "JOB", nullable = false, length = 50)),
			@AttributeOverride(name = "schedule", column = @Column(name = "SCHEDULE", nullable = false, length = 50)) })
	public RelatSliSchedId getId() {
		return this.id;
	}

	public void setId(RelatSliSchedId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHEDULE", nullable = false, insertable = false, updatable = false)
	public Scheduler getScheduler() {
		return this.scheduler;
	}

	public void setScheduler(Scheduler scheduler) {
		this.scheduler = scheduler;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB", nullable = false, insertable = false, updatable = false)
	public Sli getSli() {
		return this.sli;
	}

	public void setSli(Sli sli) {
		this.sli = sli;
	}

}
