package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatSliSchedId generated by hbm2java
 */
@Embeddable
public class RelatSliSchedId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -397076336220462121L;
	private String job;
	private String schedule;

	public RelatSliSchedId() {
	}

	public RelatSliSchedId(String job, String schedule) {
		this.job = job;
		this.schedule = schedule;
	}

	@Column(name = "JOB", nullable = false, length = 50)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "SCHEDULE", nullable = false, length = 50)
	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelatSliSchedId))
			return false;
		RelatSliSchedId castOther = (RelatSliSchedId) other;

		return ((this.getJob() == castOther.getJob()) || (this.getJob() != null
				&& castOther.getJob() != null && this.getJob().equals(
				castOther.getJob())))
				&& ((this.getSchedule() == castOther.getSchedule()) || (this
						.getSchedule() != null
						&& castOther.getSchedule() != null && this
						.getSchedule().equals(castOther.getSchedule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJob() == null ? 0 : this.getJob().hashCode());
		result = 37 * result
				+ (getSchedule() == null ? 0 : this.getSchedule().hashCode());
		return result;
	}

}
