package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatDatacomId generated by hbm2java
 */
@Embeddable
public class RelatDatacomId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5243402239550530700L;
	private String dataview;
	private String programs;
	private String versionPg;
	private String system;

	public RelatDatacomId() {
	}

	public RelatDatacomId(String dataview, String programs, String versionPg,
			String system) {
		this.dataview = dataview;
		this.programs = programs;
		this.versionPg = versionPg;
		this.system = system;
	}

	@Column(name = "DATAVIEW", nullable = false, length = 50)
	public String getDataview() {
		return this.dataview;
	}

	public void setDataview(String dataview) {
		this.dataview = dataview;
	}

	@Column(name = "PROGRAMS", nullable = false, length = 50)
	public String getPrograms() {
		return this.programs;
	}

	public void setPrograms(String programs) {
		this.programs = programs;
	}

	@Column(name = "VERSION_PG", nullable = false, length = 50)
	public String getVersionPg() {
		return this.versionPg;
	}

	public void setVersionPg(String versionPg) {
		this.versionPg = versionPg;
	}

	@Column(name = "SYSTEM", nullable = false, length = 50)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelatDatacomId))
			return false;
		RelatDatacomId castOther = (RelatDatacomId) other;

		return ((this.getDataview() == castOther.getDataview()) || (this
				.getDataview() != null && castOther.getDataview() != null && this
				.getDataview().equals(castOther.getDataview())))
				&& ((this.getPrograms() == castOther.getPrograms()) || (this
						.getPrograms() != null
						&& castOther.getPrograms() != null && this
						.getPrograms().equals(castOther.getPrograms())))
				&& ((this.getVersionPg() == castOther.getVersionPg()) || (this
						.getVersionPg() != null
						&& castOther.getVersionPg() != null && this
						.getVersionPg().equals(castOther.getVersionPg())))
				&& ((this.getSystem() == castOther.getSystem()) || (this
						.getSystem() != null && castOther.getSystem() != null && this
						.getSystem().equals(castOther.getSystem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDataview() == null ? 0 : this.getDataview().hashCode());
		result = 37 * result
				+ (getPrograms() == null ? 0 : this.getPrograms().hashCode());
		result = 37 * result
				+ (getVersionPg() == null ? 0 : this.getVersionPg().hashCode());
		result = 37 * result
				+ (getSystem() == null ? 0 : this.getSystem().hashCode());
		return result;
	}

}
