package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RunPrgId generated by hbm2java
 */
@Embeddable
public class RunPrgId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2106252583569844632L;
	private String jobAppel;
	private String programs;
	private String version;
	private String system;

	public RunPrgId() {
	}

	public RunPrgId(String jobAppel, String programs, String version,
			String system) {
		this.jobAppel = jobAppel;
		this.programs = programs;
		this.version = version;
		this.system = system;
	}

	@Column(name = "JOB_APPEL", nullable = false, length = 50)
	public String getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(String jobAppel) {
		this.jobAppel = jobAppel;
	}

	@Column(name = "PROGRAMS", nullable = false, length = 50)
	public String getPrograms() {
		return this.programs;
	}

	public void setPrograms(String programs) {
		this.programs = programs;
	}

	@Column(name = "VERSION", nullable = false, length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "SYSTEM", nullable = false, length = 50)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RunPrgId))
			return false;
		RunPrgId castOther = (RunPrgId) other;

		return ((this.getJobAppel() == castOther.getJobAppel()) || (this
				.getJobAppel() != null && castOther.getJobAppel() != null && this
				.getJobAppel().equals(castOther.getJobAppel())))
				&& ((this.getPrograms() == castOther.getPrograms()) || (this
						.getPrograms() != null
						&& castOther.getPrograms() != null && this
						.getPrograms().equals(castOther.getPrograms())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getSystem() == castOther.getSystem()) || (this
						.getSystem() != null && castOther.getSystem() != null && this
						.getSystem().equals(castOther.getSystem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobAppel() == null ? 0 : this.getJobAppel().hashCode());
		result = 37 * result
				+ (getPrograms() == null ? 0 : this.getPrograms().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getSystem() == null ? 0 : this.getSystem().hashCode());
		return result;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.jobAppel+" "+this.programs+" "+this.system;
	}

}
