package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RunPrg generated by hbm2java
 */
@Entity
@Table(name = "RUN_PRG", schema = "INTEGRATEUR")
public class RunPrg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5590682573402009146L;
	private RunPrgId id;
	private JobAppel jobAppel;
	private Programs programs;

	public RunPrg() {
	}

	public RunPrg(RunPrgId id, JobAppel jobAppel, Programs programs) {
		this.id = id;
		this.jobAppel = jobAppel;
		this.programs = programs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobAppel", column = @Column(name = "JOB_APPEL", nullable = false, length = 50)),
			@AttributeOverride(name = "programs", column = @Column(name = "PROGRAMS", nullable = false, length = 50)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false, length = 50)),
			@AttributeOverride(name = "system", column = @Column(name = "SYSTEM", nullable = false, length = 50)) })
	public RunPrgId getId() {
		return this.id;
	}

	public void setId(RunPrgId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_APPEL", nullable = false, insertable = false, updatable = false)
	public JobAppel getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(JobAppel jobAppel) {
		this.jobAppel = jobAppel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PROGRAMS", referencedColumnName = "NAME", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "VERSION", referencedColumnName = "VERSION", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SYSTEM", referencedColumnName = "SYSTEM", nullable = false, insertable = false, updatable = false) })
	public Programs getPrograms() {
		return this.programs;
	}

	public void setPrograms(Programs programs) {
		this.programs = programs;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.id+"";
	}

}
