package manage.appli.patri.awb.modele;

// Generated 7 mai 2012 12:45:56 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Scheduler generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULER", schema = "INTEGRATEUR")
public class Scheduler implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String schedule;
	private String autoselect;
	private BigDecimal nombresJobs;
	private String description;
	private Set<RelatSliSched> relatSliScheds = new HashSet<RelatSliSched>(0);

	public Scheduler() {
	}

	public Scheduler(String schedule, String autoselect) {
		this.schedule = schedule;
		this.autoselect = autoselect;
	}

	public Scheduler(String schedule, String autoselect,
			BigDecimal nombresJobs, String description,
			Set<RelatSliSched> relatSliScheds) {
		this.schedule = schedule;
		this.autoselect = autoselect;
		this.nombresJobs = nombresJobs;
		this.description = description;
		this.relatSliScheds = relatSliScheds;
	}

	@Id
	@Column(name = "SCHEDULE", unique = true, nullable = false, length = 50)
	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	@Column(name = "AUTOSELECT", nullable = false, length = 50)
	public String getAutoselect() {
		return this.autoselect;
	}

	public void setAutoselect(String autoselect) {
		this.autoselect = autoselect;
	}

	@Column(name = "NOMBRES_JOBS", precision = 8)
	public BigDecimal getNombresJobs() {
		return this.nombresJobs;
	}

	public void setNombresJobs(BigDecimal nombresJobs) {
		this.nombresJobs = nombresJobs;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduler")
	public Set<RelatSliSched> getRelatSliScheds() {
		return this.relatSliScheds;
	}

	public void setRelatSliScheds(Set<RelatSliSched> relatSliScheds) {
		this.relatSliScheds = relatSliScheds;
	}

}
