package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sli generated by hbm2java
 */
@Entity
@Table(name = "SLI", schema = "INTEGRATEUR")
public class Sli implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1943694077845219348L;
	private String job;
	private JobAppel jobAppel;
	private String nbJob;
	private String libmemb;
	private String class_;
	private String sublib;
	private String sysid;
	private String failCode;
	private Set<RelatSliSched> relatSliScheds = new HashSet<RelatSliSched>(0);

	public Sli() {
	}

	public Sli(String job, String libmemb) {
		this.job = job;
		this.libmemb = libmemb;
	}

	public Sli(String job, JobAppel jobAppel, String nbJob, String libmemb,
			String class_, String sublib, String sysid, String failCode,
			Set<RelatSliSched> relatSliScheds) {
		this.job = job;
		this.jobAppel = jobAppel;
		this.nbJob = nbJob;
		this.libmemb = libmemb;
		this.class_ = class_;
		this.sublib = sublib;
		this.sysid = sysid;
		this.failCode = failCode;
		this.relatSliScheds = relatSliScheds;
	}

	@Id
	@Column(name = "JOB", unique = true, nullable = false, length = 50)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_APPEL")
	public JobAppel getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(JobAppel jobAppel) {
		this.jobAppel = jobAppel;
	}

	@Column(name = "NB_JOB", length = 50)
	public String getNbJob() {
		return this.nbJob;
	}

	public void setNbJob(String nbJob) {
		this.nbJob = nbJob;
	}

	@Column(name = "LIBMEMB", nullable = false, length = 50)
	public String getLibmemb() {
		return this.libmemb;
	}

	public void setLibmemb(String libmemb) {
		this.libmemb = libmemb;
	}

	@Column(name = "CLASS", length = 50)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "SUBLIB", length = 50)
	public String getSublib() {
		return this.sublib;
	}

	public void setSublib(String sublib) {
		this.sublib = sublib;
	}

	@Column(name = "SYSID", length = 50)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "FAIL_CODE", length = 50)
	public String getFailCode() {
		return this.failCode;
	}

	public void setFailCode(String failCode) {
		this.failCode = failCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sli")
	public Set<RelatSliSched> getRelatSliScheds() {
		return this.relatSliScheds;
	}

	public void setRelatSliScheds(Set<RelatSliSched> relatSliScheds) {
		this.relatSliScheds = relatSliScheds;
	}

}
