package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TableAwb generated by hbm2java
 */
@Entity
@Table(name = "TABLE_AWB", schema = "INTEGRATEUR")
public class TableAwb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8217625405034099002L;
	private String name;
	private AreaAwb areaAwb;
	private Set<DataviewDatacom> dataviewDatacoms = new HashSet<DataviewDatacom>(
			0);

	public TableAwb() {
	}

	public TableAwb(String name, AreaAwb areaAwb) {
		this.name = name;
		this.areaAwb = areaAwb;
	}

	public TableAwb(String name, AreaAwb areaAwb,
			Set<DataviewDatacom> dataviewDatacoms) {
		this.name = name;
		this.areaAwb = areaAwb;
		this.dataviewDatacoms = dataviewDatacoms;
	}

	@Id
	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AREA_NAME", nullable = false)
	public AreaAwb getAreaAwb() {
		return this.areaAwb;
	}

	public void setAreaAwb(AreaAwb areaAwb) {
		this.areaAwb = areaAwb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tableAwb")
	public Set<DataviewDatacom> getDataviewDatacoms() {
		return this.dataviewDatacoms;
	}

	public void setDataviewDatacoms(Set<DataviewDatacom> dataviewDatacoms) {
		this.dataviewDatacoms = dataviewDatacoms;
	}

}
