package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Urt generated by hbm2java
 */
@Entity
@Table(name = "URT", schema = "INTEGRATEUR")
public class Urt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2576291084575111281L;
	private UrtId id;
	private JobAppel jobAppel;

	public Urt() {
	}

	public Urt(UrtId id, JobAppel jobAppel) {
		this.id = id;
		this.jobAppel = jobAppel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobAppel", column = @Column(name = "JOB_APPEL", nullable = false, length = 50)),
			@AttributeOverride(name = "urt", column = @Column(name = "URT", length = 50)) })
	public UrtId getId() {
		return this.id;
	}

	public void setId(UrtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_APPEL", nullable = false, insertable = false, updatable = false)
	public JobAppel getJobAppel() {
		return this.jobAppel;
	}

	public void setJobAppel(JobAppel jobAppel) {
		this.jobAppel = jobAppel;
	}

}
