package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsePgmId generated by hbm2java
 */
@Embeddable
public class UsePgmId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5764913790136700332L;
	private String name;
	private String version;
	private String system;
	private String calledPgmName;
	private String calledPgmVers;
	private String calledPgmSys;

	public UsePgmId() {
	}

	public UsePgmId(String calledPgmName, String calledPgmVers,
			String calledPgmSys) {
		this.calledPgmName = calledPgmName;
		this.calledPgmVers = calledPgmVers;
		this.calledPgmSys = calledPgmSys;
	}

	public UsePgmId(String name, String version, String system,
			String calledPgmName, String calledPgmVers, String calledPgmSys) {
		this.name = name;
		this.version = version;
		this.system = system;
		this.calledPgmName = calledPgmName;
		this.calledPgmVers = calledPgmVers;
		this.calledPgmSys = calledPgmSys;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VERSION", length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "SYSTEM", length = 50)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "CALLED_PGM_NAME", nullable = false, length = 50)
	public String getCalledPgmName() {
		return this.calledPgmName;
	}

	public void setCalledPgmName(String calledPgmName) {
		this.calledPgmName = calledPgmName;
	}

	@Column(name = "CALLED_PGM_VERS", nullable = false, length = 50)
	public String getCalledPgmVers() {
		return this.calledPgmVers;
	}

	public void setCalledPgmVers(String calledPgmVers) {
		this.calledPgmVers = calledPgmVers;
	}

	@Column(name = "CALLED_PGM_SYS", nullable = false, length = 50)
	public String getCalledPgmSys() {
		return this.calledPgmSys;
	}

	public void setCalledPgmSys(String calledPgmSys) {
		this.calledPgmSys = calledPgmSys;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsePgmId))
			return false;
		UsePgmId castOther = (UsePgmId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getSystem() == castOther.getSystem()) || (this
						.getSystem() != null && castOther.getSystem() != null && this
						.getSystem().equals(castOther.getSystem())))
				&& ((this.getCalledPgmName() == castOther.getCalledPgmName()) || (this
						.getCalledPgmName() != null
						&& castOther.getCalledPgmName() != null && this
						.getCalledPgmName()
						.equals(castOther.getCalledPgmName())))
				&& ((this.getCalledPgmVers() == castOther.getCalledPgmVers()) || (this
						.getCalledPgmVers() != null
						&& castOther.getCalledPgmVers() != null && this
						.getCalledPgmVers()
						.equals(castOther.getCalledPgmVers())))
				&& ((this.getCalledPgmSys() == castOther.getCalledPgmSys()) || (this
						.getCalledPgmSys() != null
						&& castOther.getCalledPgmSys() != null && this
						.getCalledPgmSys().equals(castOther.getCalledPgmSys())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getSystem() == null ? 0 : this.getSystem().hashCode());
		result = 37
				* result
				+ (getCalledPgmName() == null ? 0 : this.getCalledPgmName()
						.hashCode());
		result = 37
				* result
				+ (getCalledPgmVers() == null ? 0 : this.getCalledPgmVers()
						.hashCode());
		result = 37
				* result
				+ (getCalledPgmSys() == null ? 0 : this.getCalledPgmSys()
						.hashCode());
		return result;
	}

}
