package manage.appli.patri.awb.modele;

// Generated 27 avr. 2012 17:38:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UseReportId generated by hbm2java
 */
@Embeddable
public class UseReportId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8460598893671692202L;
	private String report;
	private String version;
	private String calledPgmName;
	private String calledPgmVers;
	private String calledPgmSys;

	public UseReportId() {
	}

	public UseReportId(String calledPgmName, String calledPgmVers,
			String calledPgmSys) {
		this.calledPgmName = calledPgmName;
		this.calledPgmVers = calledPgmVers;
		this.calledPgmSys = calledPgmSys;
	}

	public UseReportId(String report, String version, String calledPgmName,
			String calledPgmVers, String calledPgmSys) {
		this.report = report;
		this.version = version;
		this.calledPgmName = calledPgmName;
		this.calledPgmVers = calledPgmVers;
		this.calledPgmSys = calledPgmSys;
	}

	@Column(name = "REPORT", length = 50)
	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	@Column(name = "VERSION", length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CALLED_PGM_NAME", nullable = false, length = 50)
	public String getCalledPgmName() {
		return this.calledPgmName;
	}

	public void setCalledPgmName(String calledPgmName) {
		this.calledPgmName = calledPgmName;
	}

	@Column(name = "CALLED_PGM_VERS", nullable = false, length = 50)
	public String getCalledPgmVers() {
		return this.calledPgmVers;
	}

	public void setCalledPgmVers(String calledPgmVers) {
		this.calledPgmVers = calledPgmVers;
	}

	@Column(name = "CALLED_PGM_SYS", nullable = false, length = 50)
	public String getCalledPgmSys() {
		return this.calledPgmSys;
	}

	public void setCalledPgmSys(String calledPgmSys) {
		this.calledPgmSys = calledPgmSys;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UseReportId))
			return false;
		UseReportId castOther = (UseReportId) other;

		return ((this.getReport() == castOther.getReport()) || (this
				.getReport() != null && castOther.getReport() != null && this
				.getReport().equals(castOther.getReport())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCalledPgmName() == castOther.getCalledPgmName()) || (this
						.getCalledPgmName() != null
						&& castOther.getCalledPgmName() != null && this
						.getCalledPgmName()
						.equals(castOther.getCalledPgmName())))
				&& ((this.getCalledPgmVers() == castOther.getCalledPgmVers()) || (this
						.getCalledPgmVers() != null
						&& castOther.getCalledPgmVers() != null && this
						.getCalledPgmVers()
						.equals(castOther.getCalledPgmVers())))
				&& ((this.getCalledPgmSys() == castOther.getCalledPgmSys()) || (this
						.getCalledPgmSys() != null
						&& castOther.getCalledPgmSys() != null && this
						.getCalledPgmSys().equals(castOther.getCalledPgmSys())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReport() == null ? 0 : this.getReport().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37
				* result
				+ (getCalledPgmName() == null ? 0 : this.getCalledPgmName()
						.hashCode());
		result = 37
				* result
				+ (getCalledPgmVers() == null ? 0 : this.getCalledPgmVers()
						.hashCode());
		result = 37
				* result
				+ (getCalledPgmSys() == null ? 0 : this.getCalledPgmSys()
						.hashCode());
		return result;
	}

}
